package de.kct.kct.dto;

import de.kct.kct.entity.Datensatz;

public record DatensatzDto(
        String leistungsart,
        Integer aarNummer,
        Integer aposType,
        String vertragsnummer,
        String vertragsbezeichnung,
        String teilvertragsnummer,
        String bestellnummer,
        String bestellnummerKunde,
        String systelPspElement,
        String systelPspElementBezeichnung,
        String aufwandskonto,
        String aufwandskontobezeichnung,
        String buchungskreis,
        String debitornummer,
        String kunde,
        String bahnstelle,
        String organisationseinheit,
        String kostenstelle,
        String sapPspElement,
        String sapPspElementBezeichnung,
        String anlagenNummer,
        String anlagenBezeichnung,
        String belasteterAarAuftrag,
        String korrekturbuchnung,
        String produktLeistung,
        String produktId,
        String leistendePerson,
        String detailangabe1,
        String detailangabe2,
        String kurzbeschreibung,
        String nutzer,
        String nutzerOe,
        String emailAdresse,
        String ipPort,
        String hostname,
        String seriennummer,
        String idgNummer,
        String imeiNummer,
        String telefonnummer,
        String ort,
        String strasseHausnummer,
        String raum,
        String leistungszeitraum,
        String preisinformation,
        String foerderung,
        String anteil,
        Integer menge,
        String mengeneinheit,
        Integer einzelpreis,
        String vkZuschlag,
        String arbeitsplatzZuschlag,
        Integer gesamtpreis,
        Integer monat,
        Integer jahr,
        String rechnungsnummer,
        String rechnungsdatum,
        String kundenkennung,
        String leistungssegment,
        String produktgruppe,
        String bestandsId,
        Integer id,
        Integer periode,

        ZusatzInfosDto zusatzInfos

) {
    public static DatensatzDto fromDatensatz(Datensatz datensatz) {
        return new DatensatzDto(datensatz.getLeistungsart(), datensatz.getAarNummer(), datensatz.getAposType(), datensatz.getVertragsnummer(), datensatz.getVertragsbezeichnung(), datensatz.getTeilvertragsnummer(), datensatz.getBestellnummer(), datensatz.getBestellnummerKunde(), datensatz.getSystelPspElement(), datensatz.getSystelPspElementBezeichnung(), datensatz.getAufwandskonto(), datensatz.getAufwandskontobezeichnung(), datensatz.getBuchungskreis(), datensatz.getDebitornummer(), datensatz.getKunde(), datensatz.getBahnstelle(), datensatz.getOrganisationseinheit(), datensatz.getKostenstelle(), datensatz.getSapPspElement(), datensatz.getSapPspElementBezeichnung(), datensatz.getAnlagenNummer(), datensatz.getAnlagenBezeichnung(), datensatz.getBelasteterAarAuftrag(), datensatz.getKorrekturbuchnung(), datensatz.getProduktLeistung(), datensatz.getProduktId(), datensatz.getLeistendePerson(), datensatz.getDetailangabe1(), datensatz.getDetailangabe2(), datensatz.getKurzbeschreibung(), datensatz.getNutzer(), datensatz.getNutzerOe(), datensatz.getEmailAdresse(), datensatz.getIpPort(), datensatz.getHostname(), datensatz.getSeriennummer(), datensatz.getIdgNummer(), datensatz.getImeiNummer(), datensatz.getTelefonnummer(), datensatz.getOrt(), datensatz.getStrasseHausnummer(), datensatz.getRaum(), datensatz.getLeistungszeitraum(), datensatz.getPreisinformation(), datensatz.getFoerderung(), datensatz.getAnteil(), datensatz.getMenge(), datensatz.getMengeneinheit(), datensatz.getEinzelpreis(), datensatz.getVkZuschlag(), datensatz.getArbeitsplatzZuschlag(), datensatz.getGesamtpreis(), datensatz.getMonat(), datensatz.getJahr(), datensatz.getRechnungsnummer(), datensatz.getRechnungsdatum(), datensatz.getKundenkennung(), datensatz.getLeistungssegment(), datensatz.getProduktgruppe(), datensatz.getBestandsId(), datensatz.getId(), datensatz.getPeriode(), ZusatzInfosDto.fromZusatzInfos(datensatz.getZusatzInfos()));
    }
}
